const galleryItemStyle = {
    height: "20rem",
    width: "20rem",
    cursor: "pointer",
    zIndex: "1",
};
const landingItemStyle = {
    height: "20rem",
    width: "20rem",
    cursor: "pointer",
    zIndex: "1",
    outline: "1px dashed hotpink",
};
const modelDetailStyle = {
    backgroundColor: "white",
    maxHeight: "95%",
    maxWidth: "80%",
    outline: "1px solid black",
    gridColumnStart: "2",
    gridColumnEnd: "-1",
    gridRowStart: "1",
    gridRowEnd: "-1",
    display: "grid",
    gridTemplateColumns: "repeat(2, auto)",
    gridTemplateRows: "auto 8rem",
    borderRadius: "0.25rem",
    margin: "auto",
    zIndex: "3",
};
const statisticsStyle = {
    position: "absolute",
    top: "0",
    right: "0",
    fontFamily: "Swiss721",
    fontWeight: "200",
    fontSize: "1rem",
    listStyleType: "none",
};

const viewParameterStyle = {
    backgroundColor: "#F9FFC7",
    fontFamily: "Swiss721",
    fontWeight: "300",
    width: "100%",
    height: "8rem",
    borderTop: "1px solid #C6C6C6",
};
const lodSelectorStyle = {
    gridColumnStart: "10",
    gridColumnEnd: "-1",
    gridRowStart: "2",
    gridRowEnd: "3",
    marginRight: "auto",
    marginLeft: "1rem",
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    columnGap: "0.5rem",
    zIndex: "9",
};
const shaderSelectorStyle = {
    width: "6rem",
    gridColumnStart: "1",
    gridColumnEnd: "7",
    gridRowStart: "2",
    gridRowEnd: "4",
    marginRight: "auto",
    marginLeft: "1rem",
    zIndex: "9",
};
const matSelectorStyle = {
    width: "6rem",
    height: "4rem",
    gridColumnStart: "5",
    gridColumnEnd: "8",
    gridRowStart: "2",
    gridRowEnd: "4",
    marginRight: "auto",
    marginLeft: "1rem",
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    zIndex: "9",
};
const colorSelectorStyle = {
    height: "2.8rem",
    width: "10rem",
    gridColumnStart: "10",
    gridColumnEnd: "-1",
    gridRowStart: "4",
    gridRowEnd: "-1",
    marginRight: "auto",
    marginLeft: "1rem",
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    columnGap: "1rem",
    zIndex: "9",
};
const wireframeContainerOuter = {
    height: "4.0rem",
    gridColumnStart: "1",
    gridColumnEnd: "15",
    gridRowStart: "3",
    gridRowEnd: "-1",
    zIndex: "8",
};
const wireframeContainerInner = {
    boxShadow: "rgba(0, 0, 0, 0.06) 0px 2px 4px 0px inset",
    backgroundColor: "#E1E7A7",
    height: "1.4rem",
    marginTop: "1.5rem",
    marginLeft: "1.5rem",
    borderRadius: "0.7rem",
    outline: "1px solid #DBDC66",
    width: "10rem",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    columnGap: "0.5rem",
    zIndex: "9",
};
const lodParameterStyle = {
    height: "1.2rem",
    marginTop: "0",
    paddingLeft: "0.5rem",
    gridColumnStart: "10",
    gridColumnEnd: "-1",
    gridRowStart: "1",
    gridRowEnd: "2",
    fontSize: "1.0rem",
    fontFamily: "Swiss721",
    fontWeight: "300",
    display: "flex",
    alignItems: "center",
    zIndex: "9",
};
const colorParameterStyle = {
    height: "1.2rem",
    marginTop: "0",
    paddingLeft: "0.5rem",
    gridColumnStart: "10",
    gridColumnEnd: "-1",
    gridRowStart: "3",
    gridRowEnd: "4",
    fontSize: "1.0rem",
    fontFamily: "Swiss721",
    fontWeight: "300",
    display: "flex",
    alignItems: "center",
    zIndex: "9",
};
const shaderParameterStyle = {
    height: "1.2rem",
    marginTop: "0",
    paddingLeft: "0.5rem",
    gridColumnStart: "1",
    gridColumnEnd: "7",
    gridRowStart: "1",
    gridRowEnd: "2",
    fontSize: "1.0rem",
    fontFamily: "Swiss721",
    fontWeight: "300",
    display: "flex",
    alignItems: "center",
    zIndex: "9",
};
const matParameterStyle = {
    height: "1.2rem",
    marginTop: "0",
    paddingLeft: "0.5rem",
    gridColumnStart: "5",
    gridColumnEnd: "8",
    gridRowStart: "1",
    gridRowEnd: "2",
    fontSize: "1.0rem",
    fontFamily: "Swiss721",
    fontWeight: "300",
    display: "flex",
    alignItems: "center",
    zIndex: "9",
};
const wireframeParameterStyle = {
    gridColumnStart: "4",
    gridColumnEnd: "14",
    gridRowStart: "3",
    gridRowEnd: "4",
    fontSize: "1.0rem",
    fontFamily: "Swiss721",
    fontWeight: "300",
    marginTop: "0.5rem",
    marginBottom: "0.25rem",
    zIndex: "9",
};
const paramHeaderStyle = {
    fontSize: "0.8rem",
    fontFamily: "Swiss721",
    fontWeight: "300",
    marginTop: "0.5rem",
    marginBottom: "0.25rem",
};
export { statisticsStyle,
            galleryItemStyle,
            modelDetailStyle,
            viewParameterStyle,
            lodSelectorStyle,
            shaderSelectorStyle,
            matSelectorStyle,
            colorSelectorStyle,
            wireframeContainerOuter, 
            wireframeContainerInner,
            lodParameterStyle,
            colorParameterStyle,
            shaderParameterStyle,
            matParameterStyle,
            wireframeParameterStyle,
            landingItemStyle,
            paramHeaderStyle};